--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : INF13-BENSALAHM
-- User name     : mohammed.bensalah
-- Time stamp    : Sun Apr 12 21:50:36 2015
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.rising_edge_dectection
-- Last modified : Mon Mar 16 15:44:02 2015.
--------------------------------------------------------------------------------



library ieee;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

entity rising_edge_dectection is
  port (
    clk                : in     std_logic;
    dcf_77_s           : in     std_logic;
    reset_n            : in     std_logic;
    rising_edge_dcf_77 : out    std_logic);
end entity rising_edge_dectection;

--------------------------------------------------------------------------------
-- Object        : Architecture design.rising_edge_dectection.behavioral
-- Last modified : Mon Mar 16 15:44:02 2015.
--------------------------------------------------------------------------------


architecture behavioral of rising_edge_dectection is

begin

end architecture behavioral ; -- of rising_edge_dectection

